# Generated by Django 5.0.1 on 2024-04-06 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_industry_state_rename_location_job_city_job_job_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='ideal_candidate',
            new_name='skills',
        ),
    ]
