# Generated by Django 5.0.1 on 2024-04-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_rename_ideal_candidate_job_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='max_experience',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AddField(
            model_name='job',
            name='min_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
