# Generated by Django 5.0.1 on 2024-04-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_resume_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
